CREATE TABLE UHAB.Alumnos(´Id_Alumno´ INT AUTO_INCREMENT NOT NULL, ´Matricula´ VARCHAR(55) NOT NULL, ´Nombre´ VARCHAR(55) NOT NULL, ´Apellidos´ VARCHAR(55) NOT NULL, 
´Email´ VARCHAR(255) NOT NULL,
PRIMARY KEY (´Id_Alumno´)) ENGINE = InnoDB;
ALTER TABLE `UHAB`.`alumnos` ADD `Id_Nota` INT(11) NOT NULL ;
ALTER TABLE `UHAB`.`alumnos` ADD `Id_Clase` INT(11) NOT NULL ;